name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create SSH directory
        run: mkdir -p ~/.ssh
      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H 51.20.8.248 >> ~/.ssh/known_hosts
      - name: Deploy API 
        env:
          EC2_USER: ubuntu
          EC2_HOST: 51.20.8.248
          EC2_KEY: ${{ secrets.EC2_SECRET }}
        run: |
          echo "Deploying the API with the latest changes..."
          echo "${{ secrets.EC2_SECRET}}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -i ec2_key.pem $EC2_USER@$EC2_HOST "cd /home/ubuntu/fastapi-book-project && git pull"
          rm ec2_key.pem
      
       
